# Generated by Django 2.1.5 on 2019-08-23 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=100)),
                ('file_size', models.IntegerField()),
                ('csv_file', models.FileField(upload_to='files/csv/')),
                ('tsv_file', models.FileField(upload_to='files/tsv/')),
                ('xlsx_file', models.FileField(upload_to='files/xlsx/')),
            ],
        ),
    ]
