# Generated by Django 2.1.5 on 2019-08-25 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file_converter', '0002_auto_20190824_1459'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='file_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='file',
            old_name='file_size',
            new_name='size',
        ),
    ]
