# Generated by Django 2.1.5 on 2019-08-25 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file_converter', '0003_auto_20190825_1411'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='file',
            new_name='url',
        ),
    ]
