# Generated by Django 2.1.5 on 2019-08-25 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_converter', '0004_auto_20190825_1419'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='size',
        ),
        migrations.AddField(
            model_name='file',
            name='data_description',
            field=models.CharField(default='Data description here...', max_length=200),
            preserve_default=False,
        ),
    ]
