# Generated by Django 2.1.5 on 2019-08-25 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file_converter', '0005_auto_20190825_1429'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='url',
            new_name='file',
        ),
    ]
