# Generated by Django 2.1.5 on 2019-08-16 19:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20190816_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 16, 22, 44, 3, 677465), verbose_name='publishing date'),
        ),
    ]
