# Generated by Django 2.1.5 on 2019-08-17 19:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20190817_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 17, 22, 19, 20, 507350), verbose_name='publishing date'),
        ),
    ]
