# Generated by Django 2.1.5 on 2019-08-23 20:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_auto_20190817_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 23, 23, 3, 51, 316444), verbose_name='publishing date'),
        ),
    ]
