# Generated by Django 2.1.5 on 2019-08-24 11:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_auto_20190823_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 24, 14, 59, 19, 900702), verbose_name='publishing date'),
        ),
    ]
