# Generated by Django 2.1.5 on 2019-08-25 11:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_auto_20190825_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 25, 14, 38, 16, 956766), verbose_name='publishing date'),
        ),
    ]
